import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Database, ScanSearch, SearchCheck, Sparkles } from 'lucide-react'

import { Header } from '@/components/layout/Header'
import { SpotlightPanel } from '@/components/effects/SpotlightPanel'

export default function Page() {
  return <div className="landing"><Header /><main><section className="hero"><div className="hero-noise" /><div className="hero-copy"><p className="eyebrow">Live evidence for dated documents</p><h1>StaleCheck</h1><p className="hero-lede">Know which facts survived. See exactly what changed, when it changed, and the sources that prove it.</p><div className="hero-actions"><Link href="/auth/sign-up" className="primary-action">Check a document <ArrowRight /></Link><a href="#method" className="text-action">See how it works</a></div></div><div className="product-stage"><div className="stage-label"><span className="live-dot" /> Real check report</div><div className="product-frame"><Image src="/stalecheck-report.png" alt="StaleCheck report showing current claim verdicts and freshness score" width={1000} height={600} priority /></div></div></section><section id="method" className="method-band"><div className="section-intro"><p className="eyebrow">A fact-checking memory</p><h2>Search the live web.<br />Remember the useful evidence.</h2><p>Every check uses fresh search results. Relevant evidence from your private history is retrieved to sharpen context, never to replace current sources.</p></div><div className="method-grid"><SpotlightPanel><SearchCheck /><span>01</span><h3>Extract checkable claims</h3><p>Gemini identifies dated assertions while preserving their exact place in your document.</p></SpotlightPanel><SpotlightPanel><ScanSearch /><span>02</span><h3>Search three engines</h3><p>Google, News, and Scholar results are gathered live and ranked by source quality.</p></SpotlightPanel><SpotlightPanel><Database /><span>03</span><h3>Build private context</h3><p>Useful evidence becomes a vector memory scoped only to your account.</p></SpotlightPanel></div></section><section className="closing-band"><Sparkles /><h2>Old notes.<br /><span className="shiny-text">Current understanding.</span></h2><Link href="/auth/sign-up" className="primary-action">Start checking <ArrowRight /></Link></section></main><footer className="site-footer"><span>StaleCheck</span><p>Evidence before certainty.</p></footer>
  </div>
}
